### ISSUE TITLE
Why not use `ch` as the unit of measure for `max-width` instead of `em`?

### ISSUE THREAD

**Issue by xyzshantaram** [Holmqvist1990/Readable#1]
Just curious.

**Comment by fholmqvist** [comment]
Old habit!

I'm not a UI designer, and have been bit by under/overflow when switching between proportional and monospace fonts the times I've used `ch` in my own websites.

Would it be more suitable to use `ch` in this case?

Cheers :)

**Comment by xyzshantaram** [comment]
Hi!
The way I understand it, `ch` is more suitable than `em` because ch gives a better idea about the _average_ width of a font, since it uses the `0` character instead of the `m` as its reference. Generally `1em` is wider than `1ch` for the same font, and IMO this makes `ch` more intuitive since you can think of `ch` as being basically the width of a character.

This probably just boils down to a preference thing, I was just curious if you had any particular reason.

Thanks for your response!

Edit: And my apologies for opening an issue for something that, in hindsight, seems frivolous.
